import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateEmployees1789468101197 implements MigrationInterface {
  name = 'CreateEmployees1789468101197';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TYPE "public"."employees_department_enum" AS ENUM('Engineering', 'Marketing', 'Sales', 'HR')`,
    );
    await queryRunner.query(
      `CREATE TABLE "employees" ("id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 101) NOT NULL, "name" character varying(100) NOT NULL, "department" "public"."employees_department_enum" NOT NULL, "salary" numeric(12,2) NOT NULL, "join_date" date NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "CHK_employees_salary_non_negative" CHECK ("salary" >= 0), CONSTRAINT "PK_employees" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_employees_department" ON "employees" ("department") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_employees_is_active" ON "employees" ("is_active") `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX "public"."IDX_employees_is_active"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_employees_department"`);
    await queryRunner.query(`DROP TABLE "employees"`);
    await queryRunner.query(`DROP TYPE "public"."employees_department_enum"`);
  }
}
