import { ApiProperty } from '@nestjs/swagger';
import { Transform } from 'class-transformer';
import {
  IsBoolean,
  IsEnum,
  IsNotEmpty,
  IsNumber,
  IsString,
  Max,
  MaxLength,
  Min,
} from 'class-validator';
import { trimString } from '../../../common/transformers/value.transformers';
import { IsDateOnly } from '../../../common/validators/is-date-only.decorator';
import { Department } from '../../departments/enums/department.enum';
import {
  EMPLOYEE_NAME_MAX_LENGTH,
  EMPLOYEE_SALARY_MAX,
} from '../employee.constants';

/** ID and Last Updated Date are generated by the system and cannot be sent. */
export class CreateEmployeeDto {
  @ApiProperty({ example: 'John Doe', maxLength: EMPLOYEE_NAME_MAX_LENGTH })
  @Transform(trimString)
  @IsString()
  @IsNotEmpty()
  @MaxLength(EMPLOYEE_NAME_MAX_LENGTH)
  name: string;

  @ApiProperty({ enum: Department, example: Department.Engineering })
  @IsEnum(Department)
  department: Department;

  @ApiProperty({ example: 65000, minimum: 0, maximum: EMPLOYEE_SALARY_MAX })
  @IsNumber({ allowNaN: false, allowInfinity: false, maxDecimalPlaces: 2 })
  @Min(0)
  @Max(EMPLOYEE_SALARY_MAX)
  salary: number;

  @ApiProperty({ example: '2023-01-15', description: 'Date in YYYY-MM-DD' })
  @IsDateOnly()
  joinDate: string;

  @ApiProperty({
    example: true,
    description: 'true = Active, false = Inactive',
  })
  @IsBoolean()
  isActive: boolean;
}
